#!/bin/bash
echo $'if [ -z "$BINARY" ]\nthen\n  echo "BINARY is not set."\n  exit 1\nfi\ni=0\nn=0\nwhile [ $n -lt ${#BINARY} ]\ndo\n  i=$(( i * 2 + ${BINARY:$n:1} ))\n  n=$(( n + 1 ))\ndone\necho $i' > script.sh && bash script.sh
